apiVersion: v1
kind: Namespace
metadata:
  name: struts1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts1
  namespace: struts1
  labels:
    app: struts1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: struts1
  template:
    metadata:
      labels:
        app: struts1
    spec:
      containers:
      - name: struts1
        image: skywalke34/struts
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: struts1
  namespace: struts1
spec:
  type: NodePort
  selector:
    app: struts1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: struts1-8080-tcp
