apiVersion: v1
kind: Namespace
metadata:
  name: struts2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts2
  namespace: struts2
  labels:
    app: struts2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: struts2
  template:
    metadata:
      labels:
        app: struts2
    spec:
      containers:
      - name: struts2
        image: skywalke34/struts
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: struts2
  namespace: struts2
spec:
  type: NodePort
  selector:
    app: struts2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: struts2-8080-tcp
